/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test5;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class FilmInfor extends javax.swing.JFrame {

    List<Info_ofFilm> list = new ArrayList();
    Info_ofFilm film;
    int index;

    /**
     * Creates new form NewJFrame
     */
    public FilmInfor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIoF = new javax.swing.JLabel();
        lblFilmCategory = new javax.swing.JLabel();
        lblFilmName = new javax.swing.JLabel();
        lblFilmStudio = new javax.swing.JLabel();
        lvlStudioMail = new javax.swing.JLabel();
        lblReleaseDate = new javax.swing.JLabel();
        cbbFilmCategory = new javax.swing.JComboBox();
        txtFilmName = new javax.swing.JTextField();
        txtFilmStudio = new javax.swing.JTextField();
        txtStudioMail = new javax.swing.JTextField();
        txtReleaseDate = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilm = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIoF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIoF.setText("INFORMATION OF FILM");

        lblFilmCategory.setText("Film category");

        lblFilmName.setText("Film name");

        lblFilmStudio.setText("Film studio");

        lvlStudioMail.setText("Studio mail");

        lblReleaseDate.setText("Release date");

        cbbFilmCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chiến tranh", "Trinh thám", "Viễn tưởng", "Hành động" }));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tblFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Film Category", "Film Name", "Film Studio", "Studio Mail", "Release Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFilm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsert)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFilmCategory)
                            .addComponent(lblFilmStudio)
                            .addComponent(lblFilmName)
                            .addComponent(lblReleaseDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFilmName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFilmStudio, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(txtReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbFilmCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblIoF, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lvlStudioMail)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudioMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblFilmCategory, lblFilmName, lblFilmStudio, lblReleaseDate, lvlStudioMail});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnExit, btnInsert, btnReset, btnUpdate});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFilmName, txtReleaseDate});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFilmStudio, txtStudioMail});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIoF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilmCategory)
                    .addComponent(cbbFilmCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilmName)
                    .addComponent(txtFilmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilmStudio)
                    .addComponent(txtFilmStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlStudioMail)
                    .addComponent(txtStudioMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReleaseDate)
                    .addComponent(txtReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnInsert)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnExit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFilmCategory, lblFilmName, lblFilmStudio, lblReleaseDate, lvlStudioMail});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        addFilm();
        fillToTable();
        saveFile();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateFilm();
        fillToTable();
        saveFile();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteFilm();
        fillToTable();
        saveFile();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        JOptionPane.showMessageDialog(this, "Thoat");
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilmMouseClicked
        index = tblFilm.getSelectedRow();
        showDetail();
    }//GEN-LAST:event_tblFilmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmInfor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbbFilmCategory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilmCategory;
    private javax.swing.JLabel lblFilmName;
    private javax.swing.JLabel lblFilmStudio;
    private javax.swing.JLabel lblIoF;
    private javax.swing.JLabel lblReleaseDate;
    private javax.swing.JLabel lvlStudioMail;
    private javax.swing.JTable tblFilm;
    private javax.swing.JTextField txtFilmName;
    private javax.swing.JTextField txtFilmStudio;
    private javax.swing.JTextField txtReleaseDate;
    private javax.swing.JTextField txtStudioMail;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        index = -1;
        cbbFilmCategory.setSelectedIndex(0);
        txtFilmName.setText("");
        txtFilmStudio.setText("");
        txtStudioMail.setText("");
        txtReleaseDate.setText("");
        JOptionPane.showMessageDialog(this, "Xoa du lieu thanh cong!!");
    }

    private void addFilm() {
        if (txtFilmName.getText().length() == 0 || txtFilmStudio.getText().length() == 0 || 
                txtStudioMail.getText().length() == 0 || txtReleaseDate.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ko de trong du lieu!!");
        } else {
            String reEmail = "\\w+@\\w+\\.[a-z]{2,4}";
            if (!txtStudioMail.getText().matches(reEmail)) {
                JOptionPane.showMessageDialog(this, "Wrong Email Format!!");
                return;
            }
                    
            film = new Info_ofFilm();
            film.setFilmCategory(cbbFilmCategory.getSelectedItem().toString());
            film.setFilmName(txtFilmName.getText());
            film.setFilmStudio(txtFilmStudio.getText());
            film.setStudioMail(txtStudioMail.getText());
            film.setReleaseDate(txtReleaseDate.getText());
            list.add(film);
        }
    }

    private void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblFilm.getModel();
        model.setRowCount(0);
        for (Info_ofFilm f : list) {
            model.addRow(new Object[]{f.getFilmCategory(), f.getFilmName(), f.getFilmStudio(), f.getStudioMail(), f.getReleaseDate()});
        }
    }

    private void saveFile() {
        try {
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Film_info.txt"));
            oos.writeObject(list);
            oos.close();
        } catch (Exception e) {
        }
    }

    private void updateFilm() {
        if (txtFilmName.getText().length() == 0 || txtFilmStudio.getText().length() == 0 || 
                txtStudioMail.getText().length() == 0 || txtReleaseDate.getText().length() == 0) {
            JOptionPane.showConfirmDialog(this, "Ko de trong du lieu!!");
        } else {
            String reEmail = "\\w+@\\w+\\.[a-z]{2,4}";
            if (!txtStudioMail.getText().matches(reEmail)) {
                JOptionPane.showMessageDialog(this, "Wrong Email Format!!");
                return;
            }
                    
            film = list.get(index);
            film.setFilmCategory(cbbFilmCategory.getSelectedItem().toString());
            film.setFilmName(txtFilmName.getText());
            film.setFilmStudio(txtFilmStudio.getText());
            film.setStudioMail(txtStudioMail.getText());
            film.setReleaseDate(txtReleaseDate.getText());
        }
    }

    private void deleteFilm() {
        if (index != -1) {
            list.remove(index);
            JOptionPane.showMessageDialog(this, "Xoa thanh cong!!");
            index = -1;
        }
    }

    private void showDetail() {
        film = list.get(index);
        cbbFilmCategory.setSelectedItem(film.getFilmCategory());
        txtFilmName.setText(film.getFilmName());
        txtFilmStudio.setText(film.getFilmStudio());
        txtStudioMail.setText(film.getStudioMail());
        txtReleaseDate.setText(film.getReleaseDate());
    }
}
